# LIST NAMES MUST END WITH _QUESTIONS

set_counting_QUESTIONS = [
"Given A = np.array([1,0,2,0,3,0,4]), count the number of non-zero elements using count_nonzero.",
"Given A = np.array([[1,0,2],[0,3,0],[4,5,0]]), count non-zero elements in the entire array.",
"Given A = np.array([[1,0,2],[0,3,0],[4,5,0]]), count non-zero elements in each row using count_nonzero with axis.",
"Given A = np.array([[1,0,2],[0,3,0],[4,5,0]]), count non-zero elements in each column using count_nonzero with axis.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), count occurrences of each integer using bincount.",
"Given A = np.array([0,1,1,2,2,2,3,3]), compute the frequency of each value using bincount.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find how many times the value 3 appears using bincount.",
"Given A = np.array([2,3,3,5,5,5,5]), compute bincount and identify the most frequent element.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find unique values using unique.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find unique values and their counts using unique.",
"Given A = np.array([5,3,5,2,3,1,2,4]), return sorted unique values using unique.",
"Given A = np.array([5,3,5,2,3,1,2,4]), return unique values along with their first occurrence indices.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), find the most frequent element using unique with return_counts.",
"Given A = np.array([3,1,2,3,4,2,1,5]), determine how many distinct elements exist using unique.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), count total non-zero elements using count_nonzero.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), count occurrences of each integer using bincount after flattening the array.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), determine the most frequent value using bincount.",
"Given A = np.array([2,2,2,3,3,4,5,5,5]), find unique elements and their counts.",
"Given A = np.array([0,0,1,1,1,2,2,3]), determine how many zeros are present using bincount.",
"Given A = np.array([4,4,4,2,2,1,3,3,3]), determine which value appears the most using unique and counts."
]

set_counting_mastery_QUESTIONS = [
"Given A = np.array([1,0,2,0,3,0,4]), count the number of non-zero elements using count_nonzero.",
"Given A = np.array([[1,0,2],[0,3,0],[4,5,0]]), count non-zero elements per row using count_nonzero with axis.",
"Given A = np.array([[1,0,2],[0,3,0],[4,5,0]]), count non-zero elements per column using count_nonzero with axis.",
"Given A = np.arange(1,13).reshape(3,4), count elements greater than 5 using count_nonzero with a condition.",
"Given A = np.arange(1,13).reshape(3,4), count even numbers in each row using count_nonzero.",
"Given A = np.array([[0,1,2],[3,0,4],[5,6,0]]), count how many zeros exist using count_nonzero.",
"Given A = np.array([[1,2,0],[0,3,4],[5,0,6]]), count elements greater than the column mean using count_nonzero.",
"Given A = np.array([0,1,1,2,2,2,3,3]), compute frequencies of each value using bincount.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), determine how many times the value 3 appears using bincount.",
"Given A = np.array([2,3,3,5,5,5,5]), compute bincount and determine the most frequent value.",
"Given A = np.array([3,1,2,3,4,2,1,5]), compute bincount and identify which value occurs least.",
"Given A = np.array([1,1,2,2,2,3]), compute bincount and return the value with maximum frequency.",
"Given A = np.array([1,3,3,5]), compute bincount and explain why missing integers still appear in the result.",
"Given A = np.array([1,2,2,3,3,3]), compute bincount and ignore zeros by filtering before applying it.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), compute bincount of all elements after flattening the array.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), return unique values using unique.",
"Given A = np.array([1,2,2,3,3,3,4,4,4,4]), return unique values and their counts.",
"Given A = np.array([5,3,5,2,3,1,2,4]), return unique values along with their first occurrence indices.",
"Given A = np.array([5,3,5,2,3,1,2,4]), return indices that can reconstruct the original array using return_inverse.",
"Given A = np.array([5,3,5,2,3,1,2,4]), reconstruct the original array from unique values and inverse indices.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), find unique elements in the entire array.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), find unique rows using unique with axis=0.",
"Given A = np.array([[1,2,2],[3,3,4],[4,4,4]]), find unique columns using unique with axis=1.",
"Given A = np.array([4,4,4,2,2,1,3,3,3]), determine the most frequent value using unique with return_counts.",
"Given A = np.array([4,4,4,2,2,1,3,3,3]), determine the least frequent value using unique with return_counts.",
"Given A = np.array([1,1,2,2,2,3,4,4]), determine how many distinct elements exist using unique.",
"Given A = np.array([0,0,1,1,1,2,2,3]), determine how many zeros appear using bincount.",
"Given A = np.array([0,1,2,2,3,3,3]), compute bincount and determine the index of the maximum count.",
"Given A = np.array([1,2,2,3,3,3,4]), compare results of bincount and unique(return_counts=True).",
"Given A = np.array([1,2,2,3,3,3,4]), verify that sum of bincount equals the length of the array."
]
