# LIST NAMES MUST END WITH _QUESTIONS

set_dtypes_tricky_QUESTIONS = [
"Given A = np.array([1,2,3], dtype=np.int8), compute A + 127 and explain the result.",
"Given A = np.array([120,10], dtype=np.int8), compute A + 20 and observe integer overflow.",
"Given A = np.array([1,2,3], dtype=np.int32) and B = np.array([1.5,2.5,3.5]), determine the dtype of A + B.",
"Given A = np.array([1,2,3], dtype=np.int32), compute A / 2 and determine the resulting dtype.",
"Given A = np.array([1,2,3], dtype=np.int32), compute A // 2 and determine the resulting dtype.",
"Given A = np.array([1.7,2.9,3.1]), convert A to integers using astype(int) and observe truncation behavior.",
"Given A = np.array([1.7,2.9,3.1]), convert A to integers using astype(np.int32) and verify the result.",
"Given A = np.array([1,2,3], dtype=np.int8), cast to float using astype and verify the new dtype.",
"Given A = np.array([1,2,3], dtype=np.int32), compute B = A.astype(np.int32, copy=False) and determine if memory is shared.",
"Given A = np.array([1,2,3], dtype=np.int32), compute B = A.astype(np.float64, copy=False) and determine if memory is shared.",
"Given A = np.array([1,256], dtype=np.int16), cast to np.int8 and observe the resulting values.",
"Given A = np.array([1,2,3,4], dtype=np.int32), reinterpret the data as np.int16 using view().",
"Given A = np.array([1,2,3,4], dtype=np.int32), determine the shape after A.view(np.int16).",
"Given A = np.array([1,2,3,4], dtype=np.int32), explain why view changes interpretation without copying.",
"Given A = np.array([1,2,3,4], dtype=np.int32), convert to bytes using view(np.uint8) and determine the resulting shape.",
"Given A = np.array([1,2,3], dtype=np.int32), determine the itemsize of the dtype.",
"Given A = np.array([1,2,3], dtype=np.int32), compute total bytes consumed by the array.",
"Given A = np.array([1,2,3], dtype=np.int32), explain the difference between dtype and itemsize.",
"Given A = np.array([1,2,3], dtype=np.int32), determine the result of A + np.array([1], dtype=np.float32).",
"Given A = np.array([True, False, True]), compute A + 1 and determine the resulting dtype.",
"Given A = np.array([True, False, True]), compute A * 3 and observe implicit casting.",
"Given A = np.array([1,2,3], dtype=np.uint8), compute A - 5 and observe unsigned integer behavior.",
"Given A = np.array([255], dtype=np.uint8), compute A + 1 and observe overflow behavior.",
"Given A = np.array([1.2,3.4,5.6], dtype=np.float32), cast to np.int16 and observe truncation.",
"Given A = np.array([1,2,3], dtype=np.int32), check the byte order using dtype.byteorder.",
"Given A = np.array([1,2,3], dtype='>i4'), convert to native byte order.",
"Given A = np.array([(1,2.0),(3,4.0)], dtype=[('x',int),('y',float)]), access the 'x' field.",
"Given A = np.array([(1,2.0),(3,4.0)], dtype=[('x',int),('y',float)]), compute the mean of field 'y'.",
"Given A = np.array([(1,2.0),(3,4.0)], dtype=[('x',int),('y',float)]), determine the dtype of the structured array.",
"Given A = np.array([(1,2.0),(3,4.0)], dtype=[('x',int),('y',float)]), explain how structured fields behave like columns."
]
