# LIST NAMES MUST END WITH _QUESTIONS

set_indexing_tricky_QUESTIONS = [
"Given A = np.arange(9).reshape(3,3), determine the result of A[[0,1],[1,2]].",
"Given A = np.arange(9).reshape(3,3), determine the shape of A[[0,1],[1,2]].",
"Given A = np.arange(9).reshape(3,3), determine the result of A[[0,1]][:,[1,2]].",
"Given A = np.arange(9).reshape(3,3), explain why A[[0,1],[1,2]] is different from A[[0,1]][:,[1,2]].",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[:,[1,2]].",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[:,1:3].",
"Given A = np.arange(12).reshape(3,4), explain why A[:,[1,2]] behaves differently than A[:,1:3].",
"Given A = np.arange(12).reshape(3,4), determine whether B = A[:,1:3] shares memory with A.",
"Given A = np.arange(12).reshape(3,4), determine whether B = A[:,[1,2]] shares memory with A.",
"Given A = np.arange(10), compute A[::-1] and determine if it is a view or copy.",
"Given A = np.arange(10), assign A[::-1] = 0 and determine the resulting array.",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[[0,2],:].",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[:,[0,2]].",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[[0,2],[1,3]].",
"Given A = np.arange(12).reshape(3,4), extract rows [0,2] and columns [1,3] using np.ix_.",
"Given A = np.arange(12).reshape(3,4), explain why np.ix_ changes the result compared to A[[0,2],[1,3]].",
"Given A = np.arange(12).reshape(3,4), create a boolean mask for elements greater than 5 and extract them.",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[A>5].",
"Given A = np.arange(12).reshape(3,4), assign -1 to elements greater than 5 using boolean indexing.",
"Given A = np.arange(12).reshape(3,4), count how many elements were replaced after boolean assignment.",
"Given A = np.arange(12).reshape(3,4), explain why A[A>5][:3] does not modify A.",
"Given A = np.arange(12).reshape(3,4), assign values [100,200,300] to elements A[A>8].",
"Given A = np.arange(12).reshape(3,4), determine if boolean indexing returns a view or copy.",
"Given A = np.arange(12).reshape(3,4), determine the result of A[:,A[0]>1].",
"Given A = np.arange(12).reshape(3,4), explain why the mask A[0]>1 works for column selection.",
"Given A = np.arange(12).reshape(3,4), create separate row and column masks and observe broadcasting behavior.",
"Given A = np.arange(12).reshape(3,4), determine the result of A[[True,False,True]].",
"Given A = np.arange(12).reshape(3,4), determine the result of A[:,[True,False,True,False]].",
"Given A = np.arange(12).reshape(3,4), explain the difference between boolean masks along rows vs columns.",
"Given A = np.arange(9).reshape(3,3), determine the result of A[[0,1,2],[0,1,2]].",
"Given A = np.arange(9).reshape(3,3), extract the diagonal using advanced indexing.",
"Given A = np.arange(9).reshape(3,3), compare A.diagonal() with A[[0,1,2],[0,1,2]].",
"Given A = np.arange(12).reshape(3,4), assign A[[0,1],[1,2]] = -1 and determine the result.",
"Given A = np.arange(12).reshape(3,4), determine why assignment with fancy indexing may update elements in unexpected order.",
"Given A = np.arange(12).reshape(3,4), explain why chained indexing like A[:,1:3][:,0] may lead to confusion.",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[...,1].",
"Given A = np.arange(12).reshape(3,4), determine the shape of A[...,1:3].",
"Given A = np.arange(12).reshape(3,4), explain how ellipsis (...) expands during indexing.",
"Given A = np.arange(12).reshape(3,4), determine the result of A[:,None,2].",
"Given A = np.arange(12).reshape(3,4), determine the resulting shape after inserting a new axis with None.",
"Given A = np.arange(12).reshape(3,4), determine whether A.T[0] is a view or copy."
]

set1_QUESTIONS = [
"Given A = np.arange(1,26).reshape(5,5), extract the entire 4th column.",
"Given A = np.arange(1,26).reshape(5,5), extract the last two rows.",
"Given A = np.arange(1,26).reshape(5,5), extract the middle 3x3 block.",
"Given A = np.arange(1,26).reshape(5,5), extract first 3 rows but columns 2–4.",
"Given A = np.arange(1,26).reshape(5,5), reverse the row order.",
"Given A = np.arange(1,26).reshape(5,5), reverse the column order.",
"Given A = np.arange(1,26).reshape(5,5), extract all even numbers using boolean indexing.",
"Given A = np.arange(1,26).reshape(5,5), replace values >15 with 0.",
"Given A = np.arange(1,26).reshape(5,5), extract the four corner elements.",
"Given A = np.arange(1,26).reshape(5,5), extract the diagonal elements."
]